export const PARKS_LOADING = 'PARKS_LOADING';
export const ADD_PARKS = 'ADD_PARKS';
export const PARKS_FAILED = 'PARKS_FAILED';

export const ADD_COMMENTS = 'ADD_COMMENTS';
export const COMMENTS_FAILED = 'COMMENTS_FAILED';
export const ADD_COMMENT = 'ADD_COMMENT';

export const PROMOTIONS_LOADING = 'PROMOTIONS_LOADING';
export const ADD_PROMOTIONS = 'ADD_PROMOTIONS';
export const PROMOTIONS_FAILED = 'PROMOTIONS_FAILED';

export const PETS_LOADING = 'PETS_LOADING';
export const ADD_PETS = 'ADD_PETS';
export const PETS_FAILED = 'PETS_FAILED';

export const ADD_FAVORITE = 'ADD_FAVORITE';
export const DELETE_FAVORITE = 'DELETE_FAVORITE'; 